// Export all teacher pages for easy importing
export { default as TeacherDashboardPage } from "./TeacherDashboardPage";
export { default as MyClassesPage } from "./MyClassesPage";
export { default as ClassStudentsPage } from "./ClassStudentsPage";
export { default as AttendanceMarkPage } from "./AttendanceMarkPage";
export { default as GradeInputPage } from "./GradeInputPage";
export { default as ClassStatisticsPage } from "./ClassStatisticsPage";
export { default as StudentEvaluationPage } from "./StudentEvaluationPage";
export { default as TeacherSchedulePage } from "./TeacherSchedulePage";
export { default as TeacherNotificationsPage } from "./TeacherNotificationsPage";
