const mongoose = require("mongoose");

/**
 * Finance Schema
 * Quản lý các giao dịch tài chính (học phí, thanh toán, hoàn tiền)
 */
const financeSchema = new mongoose.Schema(
  {
    transactionCode: {
      type: String,
      unique: true,
      sparse: true, // Allow multiple null values
      // Will be auto-generated by pre-save hook if not provided
    },
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      required: true,
    },
    course: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Course",
      required: true,
    },
    type: {
      type: String,
      enum: ["tuition", "registration", "material", "exam", "refund", "other"],
      required: true,
    },
    amount: {
      type: Number,
      required: [true, "Số tiền là bắt buộc"],
      min: 0,
    },
    paymentMethod: {
      type: String,
      enum: ["cash", "bank_transfer", "credit_card", "momo", "other"],
      required: true,
    },
    status: {
      type: String,
      enum: ["pending", "paid", "partial", "overdue", "refunded", "cancelled"],
      default: "pending",
    },
    paidAmount: {
      type: Number,
      default: 0,
      min: 0,
    },
    remainingAmount: {
      type: Number,
      default: 0,
      min: 0,
    },
    dueDate: Date,
    paidDate: Date,
    receipt: {
      number: String,
      url: String,
      issuedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      issuedAt: Date,
    },
    description: {
      type: String,
      trim: true,
    },
    notes: {
      type: String,
      trim: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes
financeSchema.index({ transactionCode: 1 });
financeSchema.index({ student: 1, status: 1 });
financeSchema.index({ course: 1 });
financeSchema.index({ paidDate: 1 });
financeSchema.index({ dueDate: 1, status: 1 });

// Auto-generate transactionCode
const Counter = require("./Counter.model");

financeSchema.pre("save", async function (next) {
  if (!this.transactionCode) {
    try {
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, "0");
      const counterId = `financeTransaction_${year}${month}`;
      const counter = await Counter.findByIdAndUpdate(
        counterId,
        { $inc: { seq: 1 } },
        { new: true, upsert: true }
      );
      this.transactionCode = `TXN${year}${month}${String(counter.seq).padStart(
        5,
        "0"
      )}`;
    } catch (err) {
      return next(err);
    }
  }
  next();
});

// Calculate remaining amount before save
financeSchema.pre("save", function (next) {
  if (this.isModified("paidAmount") || this.isModified("amount")) {
    this.remainingAmount = Math.max(0, this.amount - this.paidAmount);

    // Only update status automatically if status was not manually set in this save
    if (!this.isModified("status")) {
      if (this.paidAmount === 0) {
        this.status = "pending";
      } else if (this.paidAmount >= this.amount) {
        this.status = "paid";
        this.paidDate = this.paidDate || new Date();
      } else {
        this.status = "partial";
      }
    }
  }
  next();
});

// Virtual for payment percentage
financeSchema.virtual("paymentPercentage").get(function () {
  if (!this.amount || this.amount === 0) return 0;
  return Math.round((this.paidAmount / this.amount) * 100);
});

// Method to check if payment is overdue
financeSchema.methods.isOverdue = function () {
  if (this.status === "paid" || this.status === "refunded") return false;
  if (!this.dueDate) return false;
  return new Date() > new Date(this.dueDate);
};

module.exports = mongoose.model("Finance", financeSchema);
